# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-02 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_auto_20181002_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='img',
            field=models.FileField(default=1, upload_to='/static/img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='price',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
