# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-02 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20181002_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
