# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-03 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_entry_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='img',
        ),
        migrations.AlterField(
            model_name='entry',
            name='file',
            field=models.ImageField(upload_to='product'),
        ),
    ]
