# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-17 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='addressee',
        ),
    ]
