# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-17 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_message_sender_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='address_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='addressee',
            new_name='sender',
        ),
    ]
