# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-17 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0012_commentproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproduct',
            name='text',
            field=models.TextField(),
        ),
    ]
