# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-19 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0014_statsproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
    ]
