# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-19 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0015_statsproductlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='entry',
            name='stats',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.StatsProduct'),
            preserve_default=False,
        ),
    ]
